# Generated by Django 4.1 on 2022-08-29 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.CharField(max_length=32, verbose_name='department title')),
            ],
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='name')),
                ('password', models.CharField(max_length=64, verbose_name='pwd')),
                ('age', models.IntegerField(verbose_name='age')),
                ('account', models.DecimalField(decimal_places=2, default=2, max_digits=10, verbose_name='account left')),
                ('date_time', models.DateTimeField(verbose_name='time')),
                ('gender', models.SmallIntegerField(choices=[(1, 'male'), (2, 'famale')], verbose_name='xingbie')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.department')),
            ],
        ),
    ]
