# Generated by Django 4.1 on 2022-08-31 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_alter_userinfo_account_alter_userinfo_date_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrettyNum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=11, verbose_name='telephone number')),
                ('price', models.IntegerField(blank=True, default=0, null=True, verbose_name='price')),
                ('level', models.SmallIntegerField(choices=[(1, 'one level'), (2, 'two level'), (3, 'three level')], default=1, verbose_name='level')),
                ('status', models.SmallIntegerField(choices=[(1, 'used'), (2, 'not used')], default=2, verbose_name='status')),
            ],
        ),
    ]
