# Generated by Django 4.1 on 2022-09-05 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField(choices=[(1, 'urgent'), (2, 'imponent'), (3, 'temporary')], default=1, verbose_name='level')),
                ('title', models.CharField(max_length=64, verbose_name='title')),
                ('detail', models.CharField(max_length=64, verbose_name='detail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.admin', verbose_name='responsible user')),
            ],
        ),
    ]
