# Generated by Django 4.1 on 2022-09-05 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='detail',
            field=models.TextField(verbose_name='detail'),
        ),
    ]
