# Generated by Django 4.1 on 2022-09-05 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_alter_task_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(max_length=32, verbose_name='order')),
                ('title', models.CharField(max_length=32, verbose_name='title')),
                ('price', models.IntegerField(verbose_name='price')),
                ('status', models.SmallIntegerField(choices=[(1, 'payed'), (2, 'Not pay')], default=1, verbose_name='status')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.admin', verbose_name='admin')),
            ],
        ),
    ]
