# Generated by Django 4.1 on 2022-09-07 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='name')),
                ('age', models.IntegerField(verbose_name='age')),
                ('img', models.CharField(max_length=32, verbose_name='head')),
            ],
        ),
    ]
