# Generated by Django 4.1 on 2022-09-07 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_alter_boss_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='name')),
                ('count', models.IntegerField(verbose_name='age')),
                ('img', models.FileField(max_length=128, upload_to='city/', verbose_name='logo')),
            ],
        ),
    ]
