# Generated by Django 4.1 on 2022-09-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='count',
            field=models.IntegerField(verbose_name='person'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=32, verbose_name='city'),
        ),
    ]
