# Generated by Django 4.1 on 2022-09-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_nvbug'),
    ]

    operations = [
        migrations.AddField(
            model_name='nvbug',
            name='DaysOpen',
            field=models.IntegerField(default=0, verbose_name='DaysOpen'),
        ),
        migrations.AlterField(
            model_name='nvbug',
            name='ModifiedDate',
            field=models.DateTimeField(verbose_name='ModifiedDate'),
        ),
    ]
