# Generated by Django 4.1 on 2022-09-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0013_nvbug_daysopen_alter_nvbug_modifieddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nvbug',
            name='Categories',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='nvbug',
            name='CustomKeywords',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='CustomKeywords'),
        ),
        migrations.AlterField(
            model_name='nvbug',
            name='Engineer',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Engineer'),
        ),
        migrations.AlterField(
            model_name='nvbug',
            name='Regression',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Regression'),
        ),
        migrations.AlterField(
            model_name='nvbug',
            name='Version',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Version'),
        ),
    ]
