# Generated by Django 4.1 on 2022-09-13 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0014_alter_nvbug_categories_alter_nvbug_customkeywords_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugChartTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(verbose_name='Date')),
                ('NewBugs', models.SmallIntegerField(verbose_name='NewBugs')),
                ('QA_Recommended_Blocker', models.SmallIntegerField(verbose_name='QA_Recommended_Blocker_Open_Bug')),
                ('All_Opening', models.SmallIntegerField(verbose_name='cuDNN_All_Opening_Bugs')),
                ('Unscrubbed_Open', models.SmallIntegerField(verbose_name='cuDNN_Unscrubbed_Open_Bugs')),
                ('Regression', models.SmallIntegerField(verbose_name='cuDNN_Regression_Open_Bugs')),
                ('QA_filed', models.SmallIntegerField(verbose_name='cuDNN_QA_filed_Open_Bugs')),
                ('Unscrubbed_QA', models.SmallIntegerField(verbose_name='Unscrubbed_QA_bugs')),
                ('Closed_This_Week', models.SmallIntegerField(verbose_name='cuDNN_Bugs_Closed_This_Week')),
            ],
        ),
    ]
