# Generated by Django 4.1 on 2022-09-13 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0015_bugcharttable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugcharttable',
            name='Date',
            field=models.CharField(max_length=50, verbose_name='Date'),
        ),
    ]
