# Generated by Django 4.1 on 2022-09-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0016_alter_bugcharttable_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='UUID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UUID', models.CharField(max_length=32, verbose_name='UUID')),
                ('CL', models.CharField(max_length=32, verbose_name='cl')),
                ('version', models.SmallIntegerField(verbose_name='version')),
            ],
        ),
    ]
