# Generated by Django 4.1 on 2022-09-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0017_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uuid',
            name='version',
            field=models.CharField(max_length=32, verbose_name='version'),
        ),
    ]
