# Generated by Django 4.1 on 2022-10-11 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0018_alter_uuid_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='log_triage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_link', models.CharField(max_length=200, verbose_name='log_link')),
                ('status', models.CharField(max_length=32, verbose_name='status')),
                ('log_result', models.CharField(max_length=200, verbose_name='log_result')),
            ],
        ),
        migrations.CreateModel(
            name='UUID_triage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UUID', models.CharField(max_length=32, verbose_name='UUID')),
                ('status', models.CharField(max_length=32, verbose_name='status')),
                ('result_excel', models.FileField(max_length=128, upload_to='uuid_result/', verbose_name='result')),
            ],
        ),
    ]
